/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'premsingh' at '5/2/17 12:54 PM' with Gradle 3.2.1
 *
 * @author premsingh, @date 5/2/17 12:54 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
